(ns site.fabricate.docs.reference.namespaces.api
  ;; {:kindly/hide-code true :kindly/hide-result true}
  {:site.fabricate.document/title "Fabricate: API"}
  (:require [site.fabricate.api :as api]
            [cybermonday.core :as md]
            [dev.onionpancakes.chassis.core :as c]
            [site.fabricate.adorn :refer [clj->hiccup]]
            [site.fabricate.dev.build.utils :as utils]
            [site.fabricate.dev.elements :as elements]
            [rewrite-clj.zip :as z]
            [rewrite-clj.parser :as parser]
            [rewrite-clj.node :as node]))

^:kindly/hide-code (def doc-ns (find-ns 'site.fabricate.api))

^{:kindly/kind :kind/hiccup}
[:div
 {:id    "top"
  :style {:display       :grid
          :grid-column   "1 / -1"
          :grid-template-columns :subgrid
          :margin-bottom "var(--space-l)"}}
 [:h1
  {:style {:background    "var(--color-blue)"
           :border-radius "var(--space-xs)"
           :color         "var(--color-sand)"
           :grid-column   "1 / -1"
           :line-height   1.0
           :margin-bottom "0em"
           :margin-top    "0em"
           :padding       "var(--space-s)"}}
  [:span {:class "main-ns"} "site." [:wbr] "fabricate." [:wbr] "api"
   #_"site.fabricate.api"] [:br] [:span {:class "ns-annotation"} "Namespace"]]
 [:div {:style {:grid-column "1 / -1" :max-width "60ch"}} (:doc (meta doc-ns))]]

;;Fabricate's API is meant to be used in 3 steps, each specified by a function
;;and a corresponding multimethod.
^{:kindly/kind :kind/hiccup}
[:ol {:class "api-toc" :style {}}
 [:li "1."
  [:a
   {:class "card-sm"
    :href  "#site.fabricate.api/plan!"
    :style {:background-color "var(--color-brown)"}} "plan!"]
  [:a
   {:class "card-sm"
    :href  "#site.fabricate.api/collect"
    :style {:background-color "var(--color-green)"}} "collect"]]
 [:li "2."
  [:a
   {:class "card-sm"
    :href  "#site.fabricate.api/assemble"
    :style {:background-color "var(--color-brown)"}} "assemble"]
  [:a
   {:class "card-sm"
    :href  "#site.fabricate.api/build"
    :style {:background-color "var(--color-green)"}} "build"]]
 [:li "3."
  [:a
   {:class "card-sm"
    :href  "#site.fabricate.api/construct!"
    :style {:background-color "var(--color-brown)"}} "construct!"]
  [:a
   {:class "card-sm"
    :href  "#site.fabricate.api/produce!"
    :style {:background-color "var(--color-green)"}} "produce!"]]]

;; The rest of this this document explains each of these steps.


^{:kindly/kind :kind/hiccup}
(elements/function-card #'api/plan!
                        {:returns
                         (list "site: a map with two keys: "
                               [:code (clj->hiccup :site.fabricate.api/entries)]
                               " with the list of entries, and "
                               [:code (clj->hiccup :site.fabricate.api/options)]
                               ", containing site-wide options.")})

;; The plan step executes a list of setup functions, and then collects the
;; initial list of entries that will be assembled during the build step. Each
;; implementation of the collect multimethod specifies a source location that
;; entries will be collected from - typically a string indicating a file path -
;; and a function that uses that location to produce a list of entries.

;; Each source can produce one or more entries. See below for an example of
;; how Fabricate uses a glob pattern string to generate a sequence of entries.


^{:kindly/kind :kind/hiccup}
(elements/multimethod-card
 #'api/collect
 {:args    [:ol [:li "Source"] [:li "Options map"]]
  :returns "A sequence of entries, specified as maps."}
 [:pre #_{:class "multimethod-example"}
  (utils/expr->hiccup '(defmethod
                        api/collect
                        "pages/**.fab"
                        [src options]
                        (mapv
                         (fn path->entry [p] ...)
                         (fs/glob (System/getProperty "user.dir") src))))])



;;The entries collected from all of the sources are flattened into a single
;;vector at the end of the plan step and returned with the site.

^{:kindly/kind :kind/hiccup}
(elements/function-card #'api/assemble {:returns "A site, specified as a map."})


;; The assemble step builds structured data for each entry generated by the
;; plan
;; step. Each entry gets passed to the build multimethod.

;; After this, each function in the sequence of tasks passed as an argument
;; gets
;; called on the resulting site, in order. This lets you do things like
;; assemble
;; additional entries - like a table of contents, index, or site map - from the
;; contents of the entries after they get built.

^{:kindly/kind :kind/hiccup}
(elements/multimethod-card
 #'api/build
 {:args    ""
  :returns [:span "An entry with the "
            [:code (clj->hiccup :site.fabricate.document/data)] " key added."]})


;; Build dispatches on two keys for each entry:
^{:kindly/kind :kind/hiccup}
[:ol {:style {:grid-column "2 / 6"}}
 [:li
  [:code {:class "language-clojure keyword"} ":site.fabricate.source/format"]]
 [:li
  [:code {:class "language-clojure keyword"}
   ":site.fabricate.document/format"]]]

;; Because of this, each implementation of collect should define a format for
;; each entry it produces.



;; When built, the entry will have a key -
^{:kindly/kind :kind/hiccup}
[:code {:class "language-clojure keyword"} ":site.fabricate.document/data"]
;;  - containing the document after its conversion into Clojure data.
;;  Fabricate's default build methods return Hiccup from one of Fabricate's 3
;;  built-in sources: Fabricate templates, Clojure source code, and Markdown
;;  files.

;; However, because it dispatches on any keyword, your implementation of build
;; can extend Fabricate to any method of representing structured information in
;; Clojure, or override these defaults.

^{:kindly/kind :kind/hiccup} (elements/function-card #'api/construct! {})

;; The construct! function uses the structured content assembled in the
;; previous
;; step to produce output pages for the site.

;; By default, they are HTML. Any other output format could be generated from
;; the entries by ^{:kindly/kind :kind/hiccup}  [:code {:class
;; "language-clojure
;; keyword"} "produce!"]

^{:kindly/kind :kind/hiccup}
(elements/multimethod-card #'api/produce!
                           {:args    [:ol [:li "An entry map"]
                                      [:li "An options map"]]
                            :returns "An entry, specified as a map."})

;; The produce! multimethod creates output for the entry passed as an argument.
;; It dispatches on two keys:

^{:kindly/kind :kind/hiccup}
[:ol {:style {:grid-column "2 / 6"}}
 [:li
  [:code {:class "language-clojure keyword"} ":site.fabricate.document/format"]]
 [:li
  [:code {:class "language-clojure keyword"} ":site.fabricate.page/format"]]]

;; The implementation will generate output of the given page format from data
;; of
;; the given document format. By default, this is a HTML file, generated from
;; the Hiccup data built in the assemble step.
^{:kindly/kind :kind/hiccup}
[:p {:class "clojure-comment"}
 "The produce! multimethod returns an entry with a key added: "
 [:code {:class "language-clojure keyword"} ":site.fabricate.page/location"]
 ". This key indicates the URL or file path of a generated page."]
#_^{:kindly/kind :kind/hiccup}
  [:figure
   {:style {:grid-column   "1 / span 4"
            :margin-bottom "var(--space-xl)"
            :margin-top    "var(--space-xl)"}}
   [:img {:src "/media/api-illustration.svg"}]]
^{:kindly/kind :kind/hiccup}
[:h2
 {:id    "in-use"
  :style {:border-bottom "solid var(--color-yellow) var(--grid-gap-x)"
          :font-size     "var(--step-4)"}} "In use"]

;;The API provides an elegant combination of extensibility and ease of use.
;;This
;;example is simplified from Fabricate's own page generation code.

^{:kindly/kind :kind/hiccup}
[:pre
 [:code {:class "language-clojure"}
  (utils/expr->hiccup '(require
                        [site.fabricate.api :as api]
                        [site.fabricate.dev.styles :as styles]
                        [site.fabricate.prototype.time :as time]
                        [site.fabricate.prototype.read :as read]
                        [site.fabricate.prototype.read.grammar :as grammar]
                        [site.fabricate.prototype.hiccup :as hiccup]
                        [dev.onionpancakes.chassis.core :as c]))]]

^{:kindly/hide-code true :kindly/hide-result true}
(def build-ns-zip
  (z/of-node (parser/parse-file-all "src/site/fabricate/dev/build.clj")))
^{:kindly/kind :kind/hiccup}
[:h3 {:style {:font-size "var(--font-medium)"}} "Setting up with "
 [:code {:class "language-clojure symbol"} "defmethod"]]

;; Before running the API's 3 main functions, the build process defines methods
;; for each of these multimethods.

^{:kindly/kind :kind/hiccup}
[:h4 {:style {:font-size "var(--step-3)"}} "1. "
 [:code {:class "language-clojure symbol"} "api/collect"]]

;; This implementation generates entries from each Fabricate template.
^{:kindly/kind :kind/hiccup}
[:pre {:id "collect-template-example" :style {:grid-column "1 / -1"}}
 [:code {:class "language-clojure"}
  (-> build-ns-zip
      (z/find-next (fn [zloc]
                     (let [n      (z/node zloc)
                           cforms (node/child-sexprs n)]
                       (and cforms
                            (= 'defmethod (first cforms))
                            (= 'api/collect (second cforms))
                            (= "pages/**.fab")))))
      z/sexpr
      utils/expr->hiccup)]]


;; To dynamically create the contents of the README from a template, Fabricate
;; also defines a single-file source for it:
^{:kindly/kind :kind/hiccup}
[:pre {:id "collect-readme-example" :style {:grid-column "1 / -1"}}
 [:code {:class "language-clojure"}
  (-> build-ns-zip
      (z/find-next (fn [zloc]
                     (let [n      (z/node zloc)
                           cforms (node/child-sexprs n)]
                       (and cforms
                            (= 'defmethod (first cforms))
                            (= 'api/collect (second cforms))
                            (= "README.md.fab")))))
      z/sexpr
      utils/expr->hiccup)]]


^{:kindly/kind :kind/hiccup}
[:h4 {:style {:font-size "var(--step-3)"}} "2. "
 [:code {:class "language-clojure symbol"} "api/build"]]
;; This implementation of the build multimethod evaluates Fabricate's templates
;; and produces Hiccup from the results.

^{:kindly/kind :kind/hiccup}
[:pre {:style {:grid-column "1 / -1"}}
 [:code {:class "language-clojure"}
  (-> build-ns-zip
      (z/find-next (fn [zloc]
                     (let [n      (z/node zloc)
                           cforms (node/child-sexprs n)]
                       (and cforms
                            (= 'defmethod (first cforms))
                            (= 'api/build (second cforms))
                            (= [:site.fabricate.read/v0 :hiccup])))))
      z/sexpr
      utils/expr->hiccup)]]

^{:kindly/kind :kind/hiccup}
[:h4 {:style {:font-size "var(--step-3)"}} "3. "
 [:code {:class "language-clojure symbol"} "api/produce!"]]

;; This implementation of the produce! generates HTML from Hiccup elements.


^{:kindly/kind :kind/hiccup}
[:pre {:style {:grid-column "1 / -1"}}
 [:code {:class "language-clojure"}
  (-> build-ns-zip
      (z/find-next (fn [zloc]
                     (let [n      (z/node zloc)
                           cforms (node/child-sexprs n)]
                       (and cforms
                            (= 'defmethod (first cforms))
                            (= 'api/produce! (second cforms))
                            (= [:hiccup :html])))))
      z/sexpr
      utils/expr->hiccup)]]

^{:kindly/kind :kind/hiccup}
[:h3 {:style {:font-size "var(--font-medium)"}}
 "Evaluating using the main API functions"]
;; Fabricate defines a few setup functions:
^{:kindly/kind :kind/hiccup}
[:pre
 [:code {:class "language-clojure"}
  (-> build-ns-zip
      (z/find-next (fn [zloc]
                     (let [n      (z/node zloc)
                           cforms (node/child-sexprs n)]
                       (and cforms
                            (= 'def (first cforms))
                            (= 'setup-tasks (second cforms))))))
      z/sexpr
      utils/expr->hiccup)]]
;; And some options:
^{:kindly/kind :kind/hiccup}
[:pre
 [:code {:class "language-clojure"}
  (-> build-ns-zip
      (z/find-next
       (fn [zloc]
         (let [n      (z/node zloc)
               cforms (node/child-sexprs n)]
           (and cforms (= 'def (first cforms)) (= 'options (second cforms))))))
      z/sexpr
      utils/expr->hiccup)]]

;; With all of that defined, this is all that Fabricate needs to do to generate
;; its own documentation:
^{:kindly/kind :kind/hiccup}
[:pre
 [:code {:class "language-clojure"}
  (utils/expr->hiccup '(->>
                        {:site.fabricate.api/options options}
                        (api/plan! setup-tasks)
                        (api/assemble [])
                        (api/construct! [])))]]
